# Configuration for a local plugin
[[plugins]]
package = "/plugins/index.js"

  # Plugin configuration
    [plugins.inputs]
    #urls = "https://www.amazon.com, https://www.flipkart.com"
    location = "Dulles:Chrome"
    connectivity = "3G"
    firstViewOnly = "true"
    runs = "1"
    emulateMobile = "true"
    block = "https://www.adblock.com"
    lighthouse = "true"
    throttleCPU = "10"
  # specs = '{"average": {"firstView": {"chromeUserTiming.CumulativeLayoutShift": 0.1,"chromeUserTiming.LargestContentfulPaint": 2500,"firstContentfulPaint": 2000,"TotalBlockingTime": 0.1}}}'


 