# Configuration for a local plugin
[[plugins]]
package = "/plugins/index.js"

  # Plugin configuration
    [plugins.inputs]
    location = "Dulles:Chrome"
    connectivity = "3G"
    firstViewOnly = "true"
    runs = "1"
    emulateMobile = "true"
    block = "https://www.adblock.com"
    lighthouse = "true"
    throttleCPU = "10"
    


 