# Configuration for a local plugin
[[plugins]]
package = "/plugins/index.js"

  # Plugin configuration
    [plugins.inputs.location]
    location = "Dulles:Chrome"
    [plugins.inputs.connectivity]
    connectivity = "3G"
    [plugins.inputs.firstViewOnly]
    firstViewOnly = "true"


 