on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@v1.1.3
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://siddhantshukla814.github.io/Queen-s-english-trivia-game-/
          label: "GitHub Action Test"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
